### ISSUE TITLE
Allow profiles to specify a set of features

### ISSUE THREAD

**Issue by SirWindfield** [SirWindfield/cargo-create#29]

**Comment by SirWindfield** [comment]
Possible implementation:
```toml
[[profiles]]
name = "bin"
git = "https://github.com/SirWindfield/zerotask-rust-bin-template"
branch = "template"

[[profiles]]
name = "lib"
git = "https://github.com/SirWindfield/zerotask-rust-lib-template"
branch = "template"
```
