### ISSUE TITLE
Add a way to rename template files

### ISSUE THREAD

**Issue by SirWindfield** [SirWindfield/cargo-create#32]
https://github.com/SirWindfield/zerotask-rust-bin-template has two features for CLIs: one that uses clap and another one that uses pico-args. Both features add a Rust module that contains all relevant code (`args.rs`). Due to current limitations, the files have to have different names though.

It would be nice if there would be a way to rename files that get included. Either through some custom syntax or some other way (introducing a new field inside the config).

```toml
# Approach 1
[[features]]
name = "cli-clap"
files = ["example_clap.rs ~> example.rs"]
[[features]]
name = "cli-pico"
files = ["example_pico.rs ~> example.rs"]
# Approach 2
[[features]]
name = "cli-clap"
files = ["example_clap.rs"]
rename = [
    ["example_clap.rs", "example.rs"]
]
[[features]]
name = "cli-pico"
files = ["example_pico.rs"]
rename = [
    ["example_pico.rs", "example.rs"]
]
```
